name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: MD-Zayed-Al-Sajed
          template: classic
          base: header, activity, repositories
          config_timezone: America/Toronto

          # Theme (dark ash + green)
          config_display: large
          config_padding: 12%
          config_output: svg
          config_order: base

          plugin_languages: yes
          plugin_languages_ignored: html, css, scss, javascript, typescript, makefile, astro, glsl
          plugin_languages_limit: 8
          plugin_languages_colors: github
          plugin_languages_sections: most-used
