name: Metrics
on:
  schedule:
    - cron: "0 6 * * *"   # daily (Toronto morning-ish)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: MD-Zayed-Al-Sajed

          # Output file
          filename: github-metrics.svg

          # Disable base sections (removes profile stats block)
          base: ""

          # Languages (only)
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss, javascript, typescript, makefile, cmake, astro, glsl, d
          plugin_languages_limit: 10
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_indepth: yes
          plugin_languages_colors: github


          # Timezone
          config_timezone: America/Toronto

          # Look & feel
          config_display: large
          config_padding: 8%
